name: Build Release Binaries

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Multi-target release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install libbrotli-dev
        run: sudo apt-get update

      - name: Build and release
        uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: |
            ./cmd/ncdtree/
            ./cmd/nj
            
